namespace AdtDataReader.Storage;

public enum AdtDataType
{
    Invalid = 0,
    Logical = 1,
    Numeric = 2,
    Date = 3,
    Character = 4,
    Memo = 5,
    Binary = 6,
    Image = 7,
    VarChar = 8,
    CompactDate = 9,
    Double = 10,
    Integer = 11,
    Short = 12,
    Time = 13,
    TimeStamp = 14,
    AutoInc = 15,
    Raw = 16,
    Currency = 17,
    Money = 18,
    Long = 19,
    CiCharacter = 20,
    RowVersion = 21,
    ModTime = 22,
    VarCharFox = 23,
    VarBinaryFox = 24,
    SystemField = 25,
    NChar = 26,
    NVarChar = 27,
    NMemo = 28,
    Guid = 29,
}
